# version omitted per modern Compose :contentReference[oaicite:6]{index=6}
services:
  web:
    build: ./app
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
    networks:
      - front

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-}"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
    networks:
      - front

  nginx:
    build: ./nginx
    env_file: .env
    ports:
      - "${PROXY_PORT}:80"
    depends_on:
      - web
    networks:
      - front

networks:
  front:
    driver: bridge
